version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install click pytest
      - run: python -m pytest
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install black
      - run: black . --check
  example:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install end-of-file
      - run: eof --check
  format:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install virtualenv
      - run: virtualenv venv
      - run: . venv/bin/activate && pip install -e .
      - run: . venv/bin/activate && eof -p src/end_of_file -c
      - run: . venv/bin/activate && eof -p tests -c

workflows:
  version: 2
  default:
    jobs:
      - example
      - format
      - test
      - lint
